import { UserEntry } from './user-entry';

export const ENTRIES: UserEntry[] = [
  { id: 1, firstName: 'Nikos', lastName: 'Alexopoulos', birthDate: '17/04/1996', email: 'nikosalex@gmail.com' },
  { id: 2, firstName: 'Giorgos', lastName: 'Andrianakis', birthDate: '02/06/1961', email: 'gandrian@gmail.com' },
  { id: 3, firstName: 'Angelina', lastName: 'Athanasiou', birthDate: '07/01/1991', email: 'angath@gmail.com' },
  { id: 4, firstName: 'Kostas', lastName: 'Bakirtzis', birthDate: '25/01/1998', email: 'kostasba@gmail.com' },
  { id: 5, firstName: 'Eirini', lastName: 'Christoforou', birthDate: '31/08/1967', email: 'chriseir@hotmail.com' },
  { id: 6, firstName: 'Agapi', lastName: 'Christoyannopoulou', birthDate: '30/04/2003', email: 'chrisagapi@gmail.com' },
  { id: 7, firstName: 'Giannis', lastName: 'Chronis', birthDate: '05/03/1977', email: 'giannis@gmail.com' },
  { id: 8, firstName: 'Vasilis', lastName: 'Calimeris', birthDate: '22/05/2000', email: 'vcalime@gmail.com' },
  { id: 9, firstName: 'Panagiotis', lastName: 'Danielopoulos', birthDate: '10/09/1991', email: 'pandaniel@gmail.com'},
  { id: 10, firstName: 'Sakis', lastName: 'Rouvas', birthDate: '27/07/2000', email: 'sakisr@gmail.com' },
  { id: 11, firstName: 'Alexandros', lastName: 'Diamandis', birthDate: '17/11/1995', email: 'diamalex@gmail.com' },
  { id: 12, firstName: 'Nicolas', lastName: 'Economos', birthDate: '22/08/1980', email: 'nikecon@gmail.com' },
  { id: 13, firstName: 'Maria', lastName: 'Papadopoulou', birthDate: '12/04/2002', email: 'mariapap@hotmail.com' },
  { id: 14, firstName: 'Heleni', lastName: 'Frangopoulou', birthDate: '12/11/1969', email: 'helenfrang@gmail.com' },
  { id: 15, firstName: 'Dimitris', lastName: 'Ganas', birthDate: '28/12/1988', email: 'dimigan@gmail.com' },
  { id: 16, firstName: 'Olga', lastName: 'Hatzi', birthDate: '06/06/1981', email: 'hatziolg@gmail.com' },
  { id: 17, firstName: 'Giannis', lastName: 'Iraklidis', birthDate: '02/03/1990', email: 'iraklg@gmail.com' },
  { id: 18, firstName: 'Giorgos', lastName: 'Iordanou', birthDate: '21/06/1991', email: 'iordgiorg@gmail.com' },
  { id: 19, firstName: 'Dimitris', lastName: 'Karras', birthDate: '24/07/1982', email: 'dimkarras@gmail.com'},
  { id: 20, firstName: 'Athanasios', lastName: ' Karagiannis', birthDate: '09/10/1998', email: 'athkara@gmail.com' },
  { id: 21, firstName: 'Maria', lastName: 'Metaxa', birthDate: '25/07/1989', email: 'mariamet@gmail.com' },
  { id: 22, firstName: 'Marianna', lastName: 'Nikolaou', birthDate: '07/05/2003', email: 'marianik@gmail.com' },
  { id: 23, firstName: 'Kostas', lastName: 'Papazoglou', birthDate: '02/10/1974', email: 'kostpap@hotmail.com' },
  { id: 24, firstName: 'Apostolos', lastName: 'Sarris', birthDate: '19/04/2004', email: 'aposarr@gmail.com' },
  { id: 25, firstName: 'Sofia', lastName: 'Yiannopoulou', birthDate: '10/07/2000', email: 'sofiay@gmail.com' },
  { id: 26, firstName: 'Heleni', lastName: 'Zika', birthDate: '27/08/1966', email: 'hzika@gmail.com' },
  { id: 27, firstName: 'Stella', lastName: 'Zafeiriou', birthDate: '03/01/1993', email: 'zafeistella@gmail.com' },
  { id: 28, firstName: 'Vasillis', lastName: 'Vasilakis', birthDate: '02/02/2001', email: 'vasillisvas@gmail.com' },
  { id: 29, firstName: 'Varvara', lastName: ' Stefanopoulou', birthDate: '30/06/1973', email: 'stefvar@gmail.com'},
  { id: 30, firstName: 'Silvia', lastName: 'Sideri', birthDate: '25/05/1969', email: 'sidersilv@gmail.com' },
];

