import { UsersEntry } from './users-entry';

export const ENTRIES: UsersEntry[] = [
  { id: 1, name: 'Nikos', lastname: 'Alexopoulos', email: 'nikosalex@gmail.com' },
  { id: 2, name: 'Giorgos', lastname: 'Andrianakis', email: 'gandrian@gmail.com' },
  { id: 3, name: 'Angelina', lastname: 'Athanasiou', email: 'angath@gmail.com' },
  { id: 4, name: 'Kostas', lastname: 'Bakirtzis', email: 'kostasba@gmail.com' },
  { id: 5, name: 'Eirini', lastname: 'Christoforou', email: 'chriseir@hotmail.com' },
  { id: 6, name: 'Agapi', lastname: 'Christoyannopoulou', email: 'chrisagapi@gmail.com' },
  { id: 7, name: 'Giannis', lastname: 'Chronis', email: 'giannis@gmail.com' },
  { id: 8, name: 'Vasilis', lastname: 'Calimeris', email: 'vcalime@gmail.com' },
  { id: 9, name: 'Panagiotis', lastname: 'Danielopoulos', email: 'pandaniel@gmail.com'},
  { id: 10, name: 'Sakis', lastname: 'Rouvas', email: 'sakisr@gmail.com' },
  { id: 11, name: 'Alexandros', lastname: 'Diamandis', email: 'diamalex@gmail.com' },
  { id: 12, name: 'Nicolas', lastname: 'Economos', email: 'nikecon@gmail.com' },
  { id: 13, name: 'Maria', lastname: 'Papadopoulou', email: 'mariapap@hotmail.com' },
  { id: 14, name: 'Heleni', lastname: 'Frangopoulou', email: 'helenfrang@gmail.com' },
  { id: 15, name: 'Dimitris', lastname: 'Ganas', email: 'dimigan@gmail.com' },
  { id: 16, name: 'Olga', lastname: 'Hatzi', email: 'hatziolg@gmail.com' },
  { id: 17, name: 'Giannis', lastname: 'Iraklidis', email: 'iraklg@gmail.com' },
  { id: 18, name: 'Giorgos', lastname: 'Iordanou', email: 'iordgiorg@gmail.com' },
  { id: 19, name: 'Dimitris', lastname: 'Karras', email: 'dimkarras@gmail.com'},
  { id: 20, name: 'Athanasios', lastname: ' Karagiannis', email: 'athkara@gmail.com' },
  { id: 21, name: 'Maria', lastname: 'Metaxa', email: 'mariamet@gmail.com' },
  { id: 22, name: 'Marianna', lastname: 'Nikolaou', email: 'marianik@gmail.com' },
  { id: 23, name: 'Kostas', lastname: 'Papazoglou', email: 'kostpap@hotmail.com' },
  { id: 24, name: 'Apostolos', lastname: 'Sarris', email: 'aposarr@gmail.com' },
  { id: 25, name: 'Sofia', lastname: 'Yiannopoulou', email: 'sofiay@gmail.com' },
  { id: 26, name: 'Heleni', lastname: 'Zika', email: 'hzika@gmail.com' },
  { id: 27, name: 'Stella', lastname: 'Zafeiriou', email: 'zafeistella@gmail.com' },
  { id: 28, name: 'Vasillis', lastname: 'Vasilakis', email: 'vasillisvas@gmail.com' },
  { id: 29, name: 'Varvara', lastname: ' Stefanopoulou', email: 'stefvar@gmail.com'},
  { id: 30, name: 'Silvia', lastname: 'Sideri', email: 'sidersilv@gmail.com' },
];

