import { UsersEntry } from './users-entry';

export const ENTRIES: UsersEntry[] = [
  { id: 1, name: 'Nikos', lastname: 'Alexopoulos', birthdate: '17/04/1996', email: 'nikosalex@gmail.com' },
  { id: 2, name: 'Giorgos', lastname: 'Andrianakis', birthdate: '02/06/1961', email: 'gandrian@gmail.com' },
  { id: 3, name: 'Angelina', lastname: 'Athanasiou', birthdate: '07/01/1991', email: 'angath@gmail.com' },
  { id: 4, name: 'Kostas', lastname: 'Bakirtzis', birthdate: '25/01/1998', email: 'kostasba@gmail.com' },
  { id: 5, name: 'Eirini', lastname: 'Christoforou', birthdate: '31/08/1967', email: 'chriseir@hotmail.com' },
  { id: 6, name: 'Agapi', lastname: 'Christoyannopoulou', birthdate: '30/04/2003', email: 'chrisagapi@gmail.com' },
  { id: 7, name: 'Giannis', lastname: 'Chronis', birthdate: '05/03/1977', email: 'giannis@gmail.com' },
  { id: 8, name: 'Vasilis', lastname: 'Calimeris', birthdate: '22/05/2000', email: 'vcalime@gmail.com' },
  { id: 9, name: 'Panagiotis', lastname: 'Danielopoulos', birthdate: '10/09/1991', email: 'pandaniel@gmail.com'},
  { id: 10, name: 'Sakis', lastname: 'Rouvas', birthdate: '27/07/2000', email: 'sakisr@gmail.com' },
  { id: 11, name: 'Alexandros', lastname: 'Diamandis', birthdate: '17/11/1995', email: 'diamalex@gmail.com' },
  { id: 12, name: 'Nicolas', lastname: 'Economos', birthdate: '22/08/1980', email: 'nikecon@gmail.com' },
  { id: 13, name: 'Maria', lastname: 'Papadopoulou', birthdate: '12/04/2002', email: 'mariapap@hotmail.com' },
  { id: 14, name: 'Heleni', lastname: 'Frangopoulou', birthdate: '12/11/1969', email: 'helenfrang@gmail.com' },
  { id: 15, name: 'Dimitris', lastname: 'Ganas', birthdate: '28/12/1988', email: 'dimigan@gmail.com' },
  { id: 16, name: 'Olga', lastname: 'Hatzi', birthdate: '06/06/1981', email: 'hatziolg@gmail.com' },
  { id: 17, name: 'Giannis', lastname: 'Iraklidis', birthdate: '02/03/1990', email: 'iraklg@gmail.com' },
  { id: 18, name: 'Giorgos', lastname: 'Iordanou', birthdate: '21/06/1991', email: 'iordgiorg@gmail.com' },
  { id: 19, name: 'Dimitris', lastname: 'Karras', birthdate: '24/07/1982', email: 'dimkarras@gmail.com'},
  { id: 20, name: 'Athanasios', lastname: ' Karagiannis', birthdate: '09/10/1998', email: 'athkara@gmail.com' },
  { id: 21, name: 'Maria', lastname: 'Metaxa', birthdate: '25/07/1989', email: 'mariamet@gmail.com' },
  { id: 22, name: 'Marianna', lastname: 'Nikolaou', birthdate: '07/05/2003', email: 'marianik@gmail.com' },
  { id: 23, name: 'Kostas', lastname: 'Papazoglou', birthdate: '02/10/1974', email: 'kostpap@hotmail.com' },
  { id: 24, name: 'Apostolos', lastname: 'Sarris', birthdate: '19/04/2004', email: 'aposarr@gmail.com' },
  { id: 25, name: 'Sofia', lastname: 'Yiannopoulou', birthdate: '10/07/2000', email: 'sofiay@gmail.com' },
  { id: 26, name: 'Heleni', lastname: 'Zika', birthdate: '27/08/1966', email: 'hzika@gmail.com' },
  { id: 27, name: 'Stella', lastname: 'Zafeiriou', birthdate: '03/01/1993', email: 'zafeistella@gmail.com' },
  { id: 28, name: 'Vasillis', lastname: 'Vasilakis', birthdate: '02/02/2001', email: 'vasillisvas@gmail.com' },
  { id: 29, name: 'Varvara', lastname: ' Stefanopoulou', birthdate: '30/06/1973', email: 'stefvar@gmail.com'},
  { id: 30, name: 'Silvia', lastname: 'Sideri', birthdate: '25/05/1969', email: 'sidersilv@gmail.com' },
];

